=== sqIRLLab/sqIRLLab.github.io/.astro/collections/home.schema.json
{
  "$ref": "#/definitions/home",
  "definitions": {
    "home": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string",
          "minLength": 1,
          "errorMessage": {
            "minLength": "Cannot be empty"
          }
        },
        "subtitle": {
          "$ref": "#/definitions/home/properties/title"
        },
        "description": {
          "$ref": "#/definitions/home/properties/title"
        },
        "email": {
          "type": "string",
          "format": "email",
          "errorMessage": {
            "format": "Must be a valid email address"
          }
        },
        "logo": {
          "type": "string",
          "pattern": "\\.(jpg|jpeg|png|gif|webp|svg)$",
          "errorMessage": {
            "pattern": "Image must be a valid image file (.jpg, .jpeg, .png, .gif, .webp, or .svg)"
          }
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "title",
        "subtitle",
        "description",
        "email",
        "logo"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== sqIRLLab/sqIRLLab.github.io/src/content/home/main.json
{
  "title": "sqIRL",
  "subtitle": "Interpretable Representation Learning",
  "description": "The Interpretable Representation Learning lab, sqIRL, at the University of Antwerp pursues fundamental research at the intersection of machine learning and interpretability/explainability. Our research focuses on the inner-workings of AI systems and the learning processes that produce them. We aim to develop AI systems that are interpretable/explainable and more efficient in their use of data and computational resources.",
  "email": "jose.oramasmogrovejo@uantwerpen.be",
  "logo": "/logo.png"
}
